version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: api-chamados
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker123
      POSTGRES_DB: api-chamados
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
